version: "2"

services:
  database:
    image: dogstudio/mariadb
    ports:
      - "3306:3306"

  web:
    image: dogstudio/php:5.6-apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./dev/public:/var/www/public"
      - "./cut:/var/www/cut"
      - "./database:/var/www/database"
