version: "2"

services:
  web:
    image: dogstudio/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./dev:/var/www/dev"

  php:
    image: dogstudio/php:5.6-fpm
    ports:
      - "9000:9000"
    volumes:
      - "./dev:/var/www/dev"
